  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  template:
    metadata:
      labels:
        role: hello
    spec:
      containers:
      - name: hello
        image: 76591745/service:v1
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8080